name: 'Generate SBOM'
description: 'A GitHub Action to generate SBOM using CycloneDX and upload it to Dependency Track.'
author: 'Your Name or Organization'
inputs:
  java_version:
    description: 'Java version to setup'
    required: true
    default: '11'
  maven_version:
    description: 'Maven version to setup'
    required: true
    default: '3.6.3'
  jira_url:
    description: 'JIRA URL for Maven build (optional)'
    required: false
  jira_token:
    description: 'JIRA token for Maven build (optional)'
    required: false
  server_hostname:
    description: 'Dependency Track server hostname'
    required: true
  api_key:
    description: 'API key for Dependency Track'
    required: true
  project_name:
    description: 'Project name for Dependency Track'
    required: true
  project_version:
    description: 'Project version for Dependency Track'
    required: true
  bom_filename:
    description: 'Filename for the BOM'
    required: false
    default: './bom.xml'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        cache: 'maven'
        token: ${{ github.token }}

    - name: Install Maven
      run: |
        MAVEN_VERSION=${{ inputs.maven_version }}
        wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
        tar -xvzf apache-maven-${MAVEN_VERSION}-bin.tar.gz
        sudo rm -rf /opt/maven
        sudo mv apache-maven-${MAVEN_VERSION} /opt/maven
        echo "export M2_HOME=/opt/maven" >> $GITHUB_ENV
        echo "export PATH=\$M2_HOME/bin:\$PATH" >> $GITHUB_ENV
      shell: bash
      
    - name: Verify Maven Version
      run: mvn -v
      shell: bash
      
    - name: Build with Maven
      run: |
        MAVEN_CMD="mvn clean install"
        if [ ! -z "${{ inputs.jira_url }}" ] && [ ! -z "${{ inputs.jira_token }}" ]; then
          MAVEN_CMD="$MAVEN_CMD -Dspring.jira.url=${{ inputs.jira_url }} -Dspring.jira.token=${{ inputs.jira_token }}"
        fi
        eval $MAVEN_CMD
      shell: bash

    - name: Create SBOM with CycloneDX
      run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom  
      shell: bash

    - name: Upload bom.xml artifact
      uses: actions/upload-artifact@v4
      with:
        name: bom-artifact
        path: target/bom.xml

    - name: Download bom.xml artifact
      uses: actions/download-artifact@v4
      with:
        name: bom-artifact

    - name: LS -LA
      run: ls -la
      shell: bash

    - name: Upload BOM to Dependency Track
      uses: DependencyTrack/gh-upload-sbom@v2.1.0
      with:
        serverHostname: ${{ inputs.server_hostname }}
        apiKey: ${{ inputs.api_key }}
        protocol: https
        projectName: ${{ inputs.project_name }}
        projectVersion: ${{ inputs.project_version }}
        bomFilename: ${{ inputs.bom_filename }}
        autoCreate: true
