name: 'Generate SBOM'
description: 'A GitHub Action to generate SBOM using CycloneDX and upload it to Dependency Track.'
author: 'Your Name or Organization'
inputs:
  java_version:
    description: 'Java version to setup'
    required: true
    default: '17'
  mvn_version:
    description: 'Maven version to setup'
    required: true
    default: '3.6.3'  # Default Maven version
  jira_url:
    description: 'JIRA URL for Maven build (optional)'
    required: false
  jira_token:
    description: 'JIRA token for Maven build (optional)'
    required: false
  server_hostname:
    description: 'Dependency Track server hostname'
    required: true
  api_key:
    description: 'API key for Dependency Track'
    required: true
  project_name:
    description: 'Project name for Dependency Track'
    required: true
  project_version:
    description: 'Project version for Dependency Track'
    required: true
  bom_filename:
    description: 'Filename for the BOM'
    required: false
    default: './bom.xml'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        cache: 'maven'
        token: ${{ github.token }}

    - name: Install Maven
      run: |
        MAVEN_VERSION=${{ inputs.mvn_version }}
        M2_HOME="/opt/apache-maven-$MAVEN_VERSION"
        
        # Download and install Maven
        wget https://mirrors.estointernet.in/apache/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
        tar -xvf apache-maven-$MAVEN_VERSION-bin.tar.gz
        sudo mv apache-maven-$MAVEN_VERSION /opt/
        
        # Set environment variables
        echo "M2_HOME=$M2_HOME" >> $GITHUB_ENV
        echo "PATH=\$M2_HOME/bin:\$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Debug Maven Environment
      run: |
        source $GITHUB_ENV  # Load the environment variables
        echo "M2_HOME is set to: $M2_HOME"
        echo "PATH is set to: $PATH"
        mvn -v  # Verify Maven version
      shell: bash

    - name: Build with Maven
      run: |
        source $GITHUB_ENV
        mvn clean install
      shell: bash

    - name: Create SBOM with CycloneDX
      run: |
        source $GITHUB_ENV
        mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom  
      shell: bash

    - name: Upload bom.xml artifact
      uses: actions/upload-artifact@v4
      with:
        name: bom-artifact
        path: target/bom.xml

    - name: Download bom.xml artifact
      uses: actions/download-artifact@v4
      with:
        name: bom-artifact

    - name: LS -LA
      run: ls -la
      shell: bash

    # Upload the BOM to Dependency Track
    - name: Upload BOM to Dependency Track
      uses: DependencyTrack/gh-upload-sbom@v2.1.0
      with:
        serverHostname: ${{ inputs.server_hostname }}
        apiKey: ${{ inputs.api_key }}
        protocol: https
        projectName: ${{ inputs.project_name }}
        projectVersion: ${{ inputs.project_version }}
        bomFilename: ${{ inputs.bom_filename }}
        autoCreate: true
